import type { NextPage } from 'next';
import Head from 'next/head';
import { RandomFox } from '../components/RandomFox';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>ReactJs con TS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://img.icons8.com/?size=512&id=122831&format=png" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline">
          Hello world!
          <RandomFox />
        </h1>
      </main>

      <footer>
      </footer>
    </div>
  )
}

export default Home
