import { useState } from 'react'
import type { MouseEventHandler } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { random } from "lodash";
// dice que no hay nada que sea lodash, ts no tiene como saber que es random y cuales son sus tipos
// hay que crear un a libreria que se llame types
// solucionado el error de lodash, ahora el error es otro, ahora es random

import { LazyImage } from '../components/RandomFox';

// es muy raro que se tenga que hacer esto en la vida real, el 90% las librerias ya tienen tipos cuando no fueron creadas con TS, el 9.99% la comunidad de JS ya escribio esos tipos
// hay un repo llamado definitely typed, que contribuyen a librerias que no lo tegan.

const myRandom = () => random(1, 123);

// ahora tiene conflicto con otra variable que se llama random

// ahora vamos a lograr que los IDs sean unicos desde la API
const generateID = () => Math.random().toString(36).substring(2,9);

const Home: NextPage = () => {

  // tambien puede ser: useState<Array<string>>

  // type IFoxImageItem = { id: string; url: string };

  // Hay que hablar de las minimas representaciones del contexto, que ene este caso no es el array:
  // Array<{ id: string, url: string }

  const [images, setImages] = useState<Array<IFoxImageItem>> ([
  ]); 

  const addNewFox: MouseEventHandler <HTMLButtonElement> = (event) => { // escuchadroes usan eventos
    const newIFoxImageItem: IFoxImageItem = {
      id: generateID(), 
      url: `https://randomfox.ca/images/${myRandom()}.jpg`, 
    }; 

  // al trabajar con TS recuerda que el 90% del tiempo las librerias ya tienen tipos, pero en un bajo porcentae o con librerias viejas sin TS, 
  // se tendra que ahcer manual, con npm, es raro seguir este camino y no esta sugerido.

  // const addNewFox = (event: { preventDefault: () => void, target: HTMLButtonElement }) => { // escuchadroes usan eventos

  //   event.preventDefault()
  //   // existen dos formas de trabajar asi, como la forma inoscente y la profesional.
  //   // a primera vista parece bien pero inmediatamente con bases de codigo se vuelve inmantenible
  //   // que pasa si queremos acceder a target?

  //   const target = event.target

  //   const newIFoxImageItem: IFoxImageItem = {
  //     id: generateID(), 
  //     url: `https://randomfox.ca/images/${random()}.jpg`, 
  //   }; 
    // ahora ya esta explicito

    // esta funcion esta implicita pero devuelve los tipos correctos!!, porque las propiedades son iguales

    setImages([
      ...images,
      newIFoxImageItem
    ]);
    window.plausible('add_fox');
  }

  // todo esta implicito, puedes revisar las clases


  // useState<Array<{ id: string, url: string }>, lo asignaremos a un tipo como props

  // ahora lo convertimos a objetos

  // const [images, setImages] = useState<string[]> ([
  //   {id: '...', url: `https://randomfox.ca/images/${random()}.jpg` }, // TS nos dice que no es string
  //   `https://randomfox.ca/images/${random()}.jpg`,
  //   `https://randomfox.ca/images/${random()}.jpg`,
  //   `https://randomfox.ca/images/${random()}.jpg`,
  // ]); // ahora ya sabe que son strings

  // HAY QUE SER EXPLICITOS, hay que usar genericos, es mejor aprenderlos practifando con estos ejercicios

  // img del tipo de never, porque tiene un array completamente vacio [], no tiene forma de adivinar que hay adentro
  // set images vienen los tipos desde react y este tipo es un dispatch, esta funcion espera a un tipo, que sea al mismo que pasamos
  // si pasamos algo de forma implicita, como un numero, resolveria que todo es un numero,

  return (
    <div>
      <Head>
        <title>ReactJs con TS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://img.icons8.com/?size=512&id=122831&format=png" />

        <script 
          defer 
          data-domain="yourdomain.com" 
          src="https://plausible.io/js/script.js"
        ></script>

      </Head>

      <main>
        <h1 className="text-3xl font-bold underline"> A random fox app! </h1>

          <button onClick={addNewFox}> New Foxes! </button> {/* pensando en funcionalidad, habra una nueva funcion para generar apartir del boton las nuevas imagenes */}

          {images.map(({ id, url }) => (
            <div key={id} className="p-4"> {/*se ageraga padding y el index, ya que siempre sera diferente*/}
              <LazyImage 
                //image={url}
                src={url} // da pie a ambas, que es menos confuso? usaremos src, porque es nativo, pero tendriamos que cambiar los tipos para que esto sea valido
                width={320}
                // height='auto' // se quitan estos elementos  porque deberia gobernar, como se va a usar el elemnto, s[olo se debe saber el src de la img y otodo lo que tiene que hacer, todo lo demas tiene que estar a la mano del elemtno padre]
                title='Random Fox' 
                className='rounded bg-gray-300'
                onClick={() => console.log('hey')} 
              /> {/*alerta porque no hace parte de los atributos del componente*/}
            </div>  // ahora necesita un key prop que viene por defaul en react pero se agregara de cualquier manera
          ))}
        
      </main>

      <footer>
      </footer>
    </div>
  )
}

export default Home
